### PR TITLE
Smart Wallet JWT Secret in Helm chart

### PR DESCRIPTION
**Pull request by MusabShakeel576**
## Proposed changes

Add "smart_wallets_jwt_secret" for accounts service in Kubernetes Helm chart.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Refactor or a modification (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by AliakseiMalyshau — COMMENTED** [review]
@MusabShakeel576 LGTM.

Quick question - the value for `smart_wallets_jwt_secret` should be the same as for other Fusebox components which are using this variable?

**Comment by MusabShakeel576** [comment]
@AliakseiMalyshau yes.

**Comment by AliakseiMalyshau** [comment]
@MusabShakeel576 as described in the Notion https://www.notion.so/Kubernetes-Update-or-add-Helm-chart-environment-variables-0691d192cd0a4fb7afce54fbcbbe0474 first you should ask me for creating the new secret variable with specific value and update Cloud Build CI process. Please next time follow the tutorial.

**Comment by MusabShakeel576** [comment]
@AliakseiMalyshau I followed the Notion docs, and "Smart Wallet JWT Secret" is not a new secret.

I've merged the PR after your LGTM approval.

**Comment by AliakseiMalyshau** [comment]
@MusabShakeel576 

image

What I missed?

Also I din't approved this PR, just say "LGTM" and asked a question.

**Pull request merged**
