### PR TITLE
Implemented fallback for Explorer and NFT subgraph

### PR DESCRIPTION
**Pull request by LiorAgnin**
## Proposed changes

Features Added
1. Service Abstraction for ERC20 and ERC721 Token Balances:
- Implemented a strategy pattern to allow switching between different services (Explorer and Unmarshal) for fetching ERC20 and ERC721 token balances.
- A fallback mechanism was added to switch to the secondary service if the primary service fails.

2 Data Transformation for Consistent Response Structure:
- Ensured that the response structure from Unmarshal matches the Explorer's response structure for ERC20 token balances.
- Added transformation logic to convert Unmarshal's response to the NFT subgraph response structure for ERC721 token balances.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Refactor or a modification (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by NikolayRn — CHANGES_REQUESTED** [review]
Hey @LiorAgnin, please add Unmarshal API key as Helm secret to apps_service component.
Except this LGTM

**Comment by LiorAgnin** [comment]
> Hey @LiorAgnin, please add Unmarshal API key as Helm secret to apps_service component.
> 
> Except this LGTM 

Ohh my bad, thanks I'll add that

**Review by NikolayRn — DISMISSED** [review]
LGTM

**Review by NikolayRn — APPROVED** [review]
LGTM

**Pull request merged**
